# Generated by Django 5.1.2 on 2024-12-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shahar nomi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="To'liq ism")),
                ('phone', models.PositiveIntegerField(verbose_name='Telefon raqam')),
                ('heard', models.CharField(max_length=200, verbose_name='Qayerda eshitgan')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padez_number', models.IntegerField(verbose_name='Padez raqami')),
                ('home_number', models.CharField(max_length=200, verbose_name='Uy raqami')),
                ('home_floor', models.IntegerField(verbose_name='Qavat')),
                ('field', models.IntegerField(verbose_name='Uy maydoni (m/kv)')),
                ('price', models.PositiveIntegerField(verbose_name='Uy narxi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('home_model_id', models.IntegerField(null=True, verbose_name='Home model ID')),
                ('busy', models.BooleanField(default=False, verbose_name='Band')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bino nomi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('padez', models.IntegerField(verbose_name='Padezlar soni')),
                ('padez_home', models.JSONField(verbose_name='Xonadonlar soni')),
                ('floor', models.IntegerField(verbose_name='Qavatlar')),
                ('status', models.BooleanField(default=False, verbose_name="Qo'shilgan")),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Shahar')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.company', verbose_name='Kompaniya'),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.building', verbose_name='Bino')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.homeinformation', verbose_name='Uy')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=15, verbose_name='Passport')),
                ('term', models.IntegerField(verbose_name="To'lov muddati (oy)")),
                ('payment', models.PositiveIntegerField(verbose_name="Oldindan to'lov")),
                ('residual', models.DecimalField(decimal_places=0, editable=False, max_digits=50, verbose_name="Qolgan to'lov")),
                ('oylik_tolov', models.DecimalField(decimal_places=0, editable=False, max_digits=50, verbose_name="Oylik to'lov")),
                ('count_month', models.IntegerField(editable=False, verbose_name='Qolgan oylar')),
                ('status', models.CharField(max_length=20, verbose_name='Holati')),
                ('debt', models.BooleanField(default=False, verbose_name='Qarzdor')),
                ('created', models.DateTimeField(verbose_name='Yaratilgan vaqti')),
                ('trash_created', models.DateTimeField(auto_now_add=True, verbose_name='Savatda yaratilgan')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientinformation', verbose_name='Mijoz')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.home', verbose_name='Uy')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=15, verbose_name='Passport')),
                ('term', models.IntegerField(verbose_name="To'lov muddati (oy)")),
                ('payment', models.PositiveIntegerField(verbose_name="Oldindan to'lov")),
                ('residual', models.DecimalField(decimal_places=0, editable=False, max_digits=50, verbose_name="Qolgan to'lov")),
                ('oylik_tolov', models.DecimalField(decimal_places=0, editable=False, max_digits=50, verbose_name="Oylik to'lov")),
                ('count_month', models.IntegerField(editable=False, verbose_name='Qolgan oylar')),
                ('residu', models.IntegerField(editable=False, verbose_name="Oydan qogan to'lov")),
                ('status', models.CharField(max_length=20, verbose_name='Holati')),
                ('debt', models.BooleanField(default=False, verbose_name='Qarzdor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientinformation', verbose_name='Mijoz')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.home', verbose_name='Uy')),
            ],
        ),
        migrations.CreateModel(
            name='Rasrochka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name="To'langan summa")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client', verbose_name='Mijoz')),
            ],
        ),
    ]
