# Generated by Django 5.1 on 2024-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinformation',
            name='field',
            field=models.FloatField(verbose_name='Uy maydoni (m/kv)'),
        ),
    ]
