# Generated by Django 5.1 on 2024-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homeinformation_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasrochka',
            name='residue',
            field=models.IntegerField(default=0, verbose_name="Qolgan to'lov"),
            preserve_default=False,
        ),
    ]
