# Generated by Django 5.1 on 2024-12-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rasrochka_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasrochka',
            name='month',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Oy'),
        ),
    ]
