# Generated by Django 5.1.4 on 2025-01-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rasrochka_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='given',
            field=models.CharField(max_length=100, null=True, verbose_name='Berilgan joyi'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_muddat',
            field=models.CharField(max_length=25, null=True, verbose_name='Amal qilish muddati'),
        ),
    ]
