# Generated by Django 5.1.4 on 2025-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_client_given_client_passport_muddat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_muddat',
            field=models.CharField(max_length=25, null=True, verbose_name='Berilgan vaqti'),
        ),
    ]
