# Generated by Django 5.1.4 on 2025-01-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_location_alter_client_passport_muddat'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinformation',
            name='xona',
            field=models.IntegerField(default=3, verbose_name='Xonalar soni'),
            preserve_default=False,
        ),
    ]
