# Generated by Django 5.1.4 on 2025-01-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeinformation_xona'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank',
            field=models.CharField(default=990, max_length=150, verbose_name='Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='inn',
            field=models.CharField(default=9876, max_length=100, verbose_name='inn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Manzil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='mfo',
            field=models.CharField(default=1, max_length=100, verbose_name='mfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='telefon',
            field=models.CharField(default=1, max_length=255, verbose_name='Telefonlar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='xp',
            field=models.CharField(default=1, max_length=100, verbose_name='x/p'),
            preserve_default=False,
        ),
    ]
