# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_company_bank_company_inn_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='direktor',
            field=models.CharField(default=1, max_length=150, verbose_name='Direktor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='telefon',
            field=models.CharField(max_length=255, verbose_name='Telefonlar '),
        ),
    ]
