# Generated by Django 5.1.4 on 2025-01-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_company_direktor_alter_company_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.building', verbose_name='Bino'),
            preserve_default=False,
        ),
    ]
