# Generated by Django 5.1.4 on 2025-01-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_home_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.building', verbose_name='Bino'),
        ),
    ]
