# Generated by Django 5.1.4 on 2025-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_home_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='home_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Xonadon narxi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Telefon raqam'),
        ),
    ]
