# Generated by Django 5.1.4 on 2025-03-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_client_home_price_alter_clientinformation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='home_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Xonadon narxi'),
        ),
    ]
