# Generated by Django 5.1.4 on 2025-03-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_client_home_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pay_date',
            field=models.PositiveIntegerField(default=20, verbose_name="To'lov qilish sanasi"),
            preserve_default=False,
        ),
    ]
