# Generated by Django 5.1.4 on 2025-03-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_client_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pay_date',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="To'lov qilish sanasi"),
        ),
    ]
