# Generated by Django 5.1.4 on 2025-03-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_client_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract',
            field=models.PositiveIntegerField(default=1, verbose_name='Shartnoma raqami'),
            preserve_default=False,
        ),
    ]
