# Generated by Django 5.1.4 on 2025-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_client_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contract',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shartnoma raqami'),
        ),
    ]
