# Generated by Django 5.1.4 on 2025-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_client_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasrochka',
            name='month',
        ),
        migrations.RemoveField(
            model_name='rasrochka',
            name='residue',
        ),
        migrations.AddField(
            model_name='rasrochka',
            name='amount_paid',
            field=models.IntegerField(default=0, verbose_name="To'langan miqdor"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rasrochka',
            name='qoldiq',
            field=models.IntegerField(default=0, editable=False, verbose_name='Oy uchun qoldiq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rasrochka',
            name='qolgan_tolov',
            field=models.IntegerField(default=1, verbose_name="Qolgan to'lov"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rasrochka',
            name='amount',
            field=models.IntegerField(verbose_name="To'lov miqdori"),
        ),
    ]
