# Generated by Django 5.1.4 on 2025-03-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_rasrochka_month_remove_rasrochka_residue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasrochka',
            name='qolgan_tolov',
        ),
    ]
