# Generated by Django 5.1.4 on 2025-03-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_rasrochka_qolgan_tolov'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasrochka',
            name='month',
            field=models.IntegerField(default=20, verbose_name='Oy raqami'),
            preserve_default=False,
        ),
    ]
