# Generated by Django 5.1.4 on 2025-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rasrochka_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasrochka',
            name='date',
            field=models.DateTimeField(verbose_name="To'lov sanasi"),
        ),
    ]
