# Generated by Django 5.1.4 on 2025-03-09 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_rasrochka_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasrochka',
            name='pay_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="O'xirgi to'lov sanasi"),
            preserve_default=False,
        ),
    ]
