# Generated by Django 5.1.4 on 2025-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_rasrochka_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasrochka',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi"),
        ),
    ]
