# Generated by Django 5.1.4 on 2025-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_rasrochka_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasrochka',
            name='date',
            field=models.DateTimeField(verbose_name="To'lov sanasi"),
        ),
    ]
